# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('detail', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('cover', models.CharField(max_length=128, verbose_name='\u5c01\u9762\u56fe\u7247')),
                ('banner_cover', models.CharField(max_length=128, verbose_name='banner\u56fe\u7247')),
                ('price', models.CharField(max_length=128, verbose_name='\u4ef7\u683c')),
                ('content', models.TextField(verbose_name='\u8be6\u60c5')),
            ],
            options={
                'verbose_name': '\u4f9b\u517b',
                'verbose_name_plural': '\u4f9b\u517b',
            },
        ),
        migrations.CreateModel(
            name='ProvideClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('detail', models.TextField(verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u4f9b\u517b\u5206\u7c7b',
                'verbose_name_plural': '\u4f9b\u517b\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='provide',
            name='provideclassification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiling.ProvideClassification', verbose_name='\u6240\u5c5e\u5206\u7c7b'),
        ),
    ]
