# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodDeedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u6807\u9898')),
                ('cover', models.CharField(max_length=128, verbose_name='\u5c01\u9762\u56fe\u7247')),
                ('sub_title1', models.CharField(default='', max_length=300, verbose_name='\u6350\u8d601\u6807\u9898')),
                ('sub_detail1', models.CharField(default='', max_length=300, verbose_name='\u6350\u8d601\u63cf\u8ff0')),
                ('sub_cover1', models.CharField(max_length=128, verbose_name='\u6350\u8d601\u56fe\u7247')),
                ('sub_price1', models.FloatField(default=0.0, verbose_name='\u4ef7\u683c1')),
                ('sub_title2', models.CharField(default='', max_length=300, verbose_name='\u6350\u8d602\u6807\u9898')),
                ('sub_detail2', models.CharField(default='', max_length=300, verbose_name='\u6350\u8d602\u63cf\u8ff0')),
                ('sub_cover2', models.CharField(max_length=128, verbose_name='\u6350\u8d602\u56fe\u7247')),
                ('sub_price2', models.FloatField(default=0.0, verbose_name='\u4ef7\u683c2')),
            ],
            options={
                'verbose_name': '\u65e5\u884c\u4e00\u5584',
                'verbose_name_plural': '\u65e5\u884c\u4e00\u5584',
            },
        ),
        migrations.RemoveField(
            model_name='mage',
            name='temple',
        ),
    ]
