# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0002_auto_20160427_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u6807\u9898')),
                ('cover', models.CharField(max_length=128, verbose_name='\u5c01\u9762')),
                ('detail', models.TextField(verbose_name='\u7b80\u8ff0')),
                ('content', models.TextField(verbose_name='\u8be6\u60c5')),
                ('address', models.TextField(verbose_name='\u5730\u5740')),
                ('people_number', models.IntegerField(default=0, verbose_name='\u4eba\u6570')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('views_count', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
            ],
            options={
                'verbose_name': '\u4e49\u5de5',
                'verbose_name_plural': '\u4e49\u5de5',
            },
        ),
        migrations.RenameModel(
            old_name='ActivityUser',
            new_name='ActivityAttendee',
        ),
        migrations.RenameModel(
            old_name='ProvideClassification',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
        migrations.RenameModel(
            old_name='VolunteersUser',
            new_name='VolunteerUser',
        ),
        migrations.DeleteModel(
            name='Volunteers',
        ),
        migrations.RenameField(
            model_name='buddhismknowledge',
            old_name='detail',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='goodraise',
            old_name='start_end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='start_end',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_end',
        ),
        migrations.RemoveField(
            model_name='provide',
            name='provideclassification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='scanner_id',
        ),
        migrations.RemoveField(
            model_name='volunteeruser',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.TextField(default='', verbose_name='\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='provide',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiling.Category', verbose_name='\u6240\u5c5e\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(verbose_name='\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='people_number',
            field=models.IntegerField(default=0, verbose_name='\u6d3b\u52a8\u5141\u8bb8\u62a5\u540d\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='provide',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='\u4ef7\u683c'),
        ),
        migrations.AddField(
            model_name='volunteeruser',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiling.Volunteer', verbose_name='\u6240\u5c5e\u4e49\u5de5'),
        ),
    ]
