# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0002_auto_20160518_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooddeedday',
            name='sub_cover1',
            field=models.CharField(default='', max_length=128, verbose_name='\u6350\u8d601\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='gooddeedday',
            name='sub_cover2',
            field=models.CharField(default='', max_length=128, verbose_name='\u6350\u8d602\u56fe\u7247'),
        ),
    ]
