# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0002_good_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_no',
            field=models.IntegerField(default=0, verbose_name='\u6392\u5e8f\u53f7'),
        ),
    ]
