# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0003_auto_20160428_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temple',
            name='mage',
        ),
        migrations.AddField(
            model_name='mage',
            name='temple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiling.Temple', verbose_name='\u6240\u5c5e\u5bfa\u5e99'),
        ),
    ]
