# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0006_mage_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u624b\u673a\u53f7'),
        ),
    ]
