# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0007_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u5bc6\u7801'),
        ),
    ]
