# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0010_auto_20160509_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
