# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0011_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mage',
            name='sentiment',
            field=models.IntegerField(default=0, verbose_name='\u4eba\u6c14'),
        ),
    ]
