# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u59d3\u540d')),
                ('gender', models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=0, verbose_name='\u6027\u522b')),
                ('mobile', models.CharField(blank=True, max_length=128, verbose_name='\u7535\u8bdd')),
                ('openid', models.CharField(blank=True, max_length=128, verbose_name='\u5fae\u4fe1OpenID')),
                ('headimgurl', models.CharField(blank=True, max_length=300, verbose_name='\u5fae\u4fe1\u5934\u50cf')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
