# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiling', '0001_initial'),
        ('ucenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiling.Good', verbose_name='\u6240\u5c5e\u5546\u54c1'),
        ),
    ]
