# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0002_auto_20160510_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.TextField(default='', verbose_name='\u5bc6\u7801'),
        ),
    ]
