# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0002_order_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucenter.Cuser', verbose_name='\u6240\u5c5e\u7528\u6237'),
        ),
    ]
