# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0004_goodid_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_url',
            field=models.CharField(default='', max_length=300, verbose_name='\u4e8c\u7ef4\u7801\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='order',
            name='prepay_id',
            field=models.CharField(default='', max_length=300, verbose_name='\u8ba2\u5355id'),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_type',
            field=models.CharField(default='', max_length=128, verbose_name='\u652f\u4ed8\u7c7b\u578b'),
        ),
    ]
