# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0004_order_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='anonymous',
            field=models.IntegerField(choices=[(0, '\u975e\u533f\u540d'), (1, '\u533f\u540d')], default=0, verbose_name='\u662f\u5426\u533f\u540d'),
        ),
    ]
