# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0005_auto_20160527_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code_url',
        ),
    ]
