# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0005_auto_20160511_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u57ce\u5e02'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u56fd\u5bb6'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u7701\u4efd'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u6635\u79f0'),
        ),
    ]
