# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0006_remove_order_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goodraise_id',
            field=models.CharField(default='', max_length=300, verbose_name='\u5584\u7b79id'),
        ),
    ]
