# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0007_order_goodraise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_success_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u652f\u4ed8\u65f6\u95f4'),
        ),
    ]
