# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0008_order_pay_success_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trade_type',
            field=models.CharField(default='\u516c\u4f17\u53f7', max_length=128, verbose_name='\u652f\u4ed8\u7c7b\u578b'),
        ),
    ]
